language: python

python:
  - "3.4"

cache:
  pip:
  apt:
  directories:
    - .tox

env:
  - TOX_ENV=py27-django14
  - TOX_ENV=py27-django15
  - TOX_ENV=py34-django15
  - TOX_ENV=py34-django16
  - TOX_ENV=py34-django17
  - TOX_ENV=py34-django18

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq $APT

after_failure:
  - cat /home/travis/.pip/pip.log

after_success:
  - coveralls

install:
  - pip install pip wheel
  - pip install -q coveralls flake8 tox

script:
  - env | sort
  - tox -e $TOX_ENV
  - flake8 --show-source --max-line-length=80 --exclude=.tox,docs,tests/settings,django_contactme/__init__.py,django_contactme/migrations django_contactme/
